export default DUMMY_ROSTER_DATA = [
  {
    Flightnr: 'FT-123',
    Date: '24/01/2024',
    'Aircraft Type': 'Boeing 747',
    Tail: 'XYZ789',
    Departure: 'AMS',
    Destination: 'ATH',
    Time_Depart: '10:00 AM',
    Time_Arrive: '12:00 PM',
    DutyID: 'FLT',
    DutyCode: 'DC456',
    Captain: 'John Doe',
    'First Officer': 'Jane Smith',
    'Flight Attendant': 'Alice Johnson',
  },
  {
    Flightnr: 'FT-456',
    Date: '25/01/2024',
    'Aircraft Type': 'Airbus A320',
    Tail: 'ABC123',
    Departure: 'JFK',
    Destination: 'LHR',
    Time_Depart: '08:30 AM',
    Time_Arrive: '11:45 AM',
    DutyID: 'SBY',
    DutyCode: 'DC789',
    Captain: 'Michael Brown',
    'First Officer': 'Emily Davis',
    'Flight Attendant': 'Bob Wilson',
  },
  {
    Flightnr: 'FT-789',
    Date: '26/01/2024',
    'Aircraft Type': 'Boeing 777',
    Tail: 'DEF456',
    Departure: 'SFO',
    Destination: 'HND',
    Time_Depart: '02:15 PM',
    Time_Arrive: '06:30 PM',
    DutyID: 'OFD',
    DutyCode: 'DC101',
    Captain: 'Sarah Johnson',
    'First Officer': 'Kevin Anderson',
    'Flight Attendant': 'Eva White',
  },
  {
    Flightnr: 'FT-101',
    Date: '27/01/2024',
    'Aircraft Type': 'Airbus A380',
    Tail: 'GHI789',
    Departure: 'DXB',
    Destination: 'LAX',
    Time_Depart: '03:45 AM',
    Time_Arrive: '08:00 AM',
    DutyID: 'POS',
    DutyCode: 'DC202',
    Captain: 'David Smith',
    'First Officer': 'Olivia Brown',
    'Flight Attendant': 'Tom Wilson',
  },
  {
    Flightnr: 'FT-202',
    Date: '28/01/2024',
    'Aircraft Type': 'Boeing 737',
    Tail: 'JKL123',
    Departure: 'ORD',
    Destination: 'CDG',
    Time_Depart: '06:20 AM',
    Time_Arrive: '10:35 AM',
    DutyID: 'DO',
    DutyCode: 'DC303',
    Captain: 'Emma Taylor',
    'First Officer': 'Daniel White',
    'Flight Attendant': 'Sophia Davis',
  },

  {
    Flightnr: 'FLT-123',
    Date: '24/01/2024',
    'Aircraft Type': 'Boeing 747',
    Tail: 'XYZ789',
    Departure: 'AMS',
    Destination: 'ATH',
    Time_Depart: '10:00 AM',
    Time_Arrive: '12:00 PM',
    DutyID: 'FLT',
    DutyCode: 'DC456',
    Captain: 'John Doe',
    'First Officer': 'Jane Smith',
    'Flight Attendant': 'Alice Johnson',
  },
  {
    Flightnr: 'FLT-456',
    Date: '24/01/2024',
    'Aircraft Type': 'Airbus A320',
    Tail: 'ABC123',
    Departure: 'JFK',
    Destination: 'LHR',
    Time_Depart: '08:30 AM',
    Time_Arrive: '11:45 AM',
    DutyID: 'SBY',
    DutyCode: 'DC789',
    Captain: 'Michael Brown',
    'First Officer': 'Emily Davis',
    'Flight Attendant': 'Bob Wilson',
  },
  {
    Flightnr: 'FLT-123',
    Date: '24/01/2024',
    'Aircraft Type': 'Boeing 747',
    Tail: 'XYZ789',
    Departure: 'AMS',
    Destination: 'ATH',
    Time_Depart: '10:00 AM',
    Time_Arrive: '12:00 PM',
    DutyID: 'FLT',
    DutyCode: 'DC456',
    Captain: 'John Doe',
    'First Officer': 'Jane Smith',
    'Flight Attendant': 'Alice Johnson',
  },
  {
    Flightnr: 'FLT-456',
    Date: '31/01/2024',
    'Aircraft Type': 'Airbus A320',
    Tail: 'ABC123',
    Departure: 'JFK',
    Destination: 'LHR',
    Time_Depart: '08:30 AM',
    Time_Arrive: '11:45 AM',
    DutyID: 'DO',
    DutyCode: 'DC789',
    Captain: 'Michael Brown',
    'First Officer': 'Emily Davis',
    'Flight Attendant': 'Bob Wilson',
  },
  {
    Flightnr: 'FLT-123',
    Date: '23/01/2024',
    'Aircraft Type': 'Boeing 747',
    Tail: 'XYZ789',
    Departure: 'AMS',
    Destination: 'ATH',
    Time_Depart: '10:00 AM',
    Time_Arrive: '12:00 PM',
    DutyID: 'POS',
    DutyCode: 'DC456',
    Captain: 'John Doe',
    'First Officer': 'Jane Smith',
    'Flight Attendant': 'Alice Johnson',
  },
  {
    Flightnr: 'FLT-456',
    Date: '03/01/2024',
    'Aircraft Type': 'Airbus A320',
    Tail: 'ABC123',
    Departure: 'JFK',
    Destination: 'LHR',
    Time_Depart: '08:30 AM',
    Time_Arrive: '11:45 AM',
    DutyID: 'SBY',
    DutyCode: 'DC789',
    Captain: 'Michael Brown',
    'First Officer': 'Emily Davis',
    'Flight Attendant': 'Bob Wilson',
  },
  {
    Flightnr: 'FLT-123',
    Date: '03/01/2024',
    'Aircraft Type': 'Boeing 747',
    Tail: 'XYZ789',
    Departure: 'AMS',
    Destination: 'ATH',
    Time_Depart: '10:00 AM',
    Time_Arrive: '12:00 PM',
    DutyID: 'OFD',
    DutyCode: 'DC456',
    Captain: 'John Doe',
    'First Officer': 'Jane Smith',
    'Flight Attendant': 'Alice Johnson',
  },
  {
    Flightnr: 'FLT-456',
    Date: '03/01/2024',
    'Aircraft Type': 'Airbus A320',
    Tail: 'ABC123',
    Departure: 'JFK',
    Destination: 'LHR',
    Time_Depart: '08:30 AM',
    Time_Arrive: '11:45 AM',
    DutyID: 'SBY',
    DutyCode: 'DC789',
    Captain: 'Michael Brown',
    'First Officer': 'Emily Davis',
    'Flight Attendant': 'Bob Wilson',
  },
  {
    Flightnr: 'FLT-123',
    Date: '10/02/2024',
    'Aircraft Type': 'Boeing 747',
    Tail: 'XYZ789',
    Departure: 'AMS',
    Destination: 'ATH',
    Time_Depart: '10:00 AM',
    Time_Arrive: '12:00 PM',
    DutyID: 'FLT',
    DutyCode: 'DC456',
    Captain: 'John Doe',
    'First Officer': 'Jane Smith',
    'Flight Attendant': 'Alice Johnson',
  },
  {
    Flightnr: 'FLT-456',
    Date: '04/01/2024',
    'Aircraft Type': 'Airbus A320',
    Tail: 'ABC123',
    Departure: 'JFK',
    Destination: 'LHR',
    Time_Depart: '08:30 AM',
    Time_Arrive: '11:45 AM',
    DutyID: 'SBY',
    DutyCode: 'DC789',
    Captain: 'Michael Brown',
    'First Officer': 'Emily Davis',
    'Flight Attendant': 'Bob Wilson',
  },
  {
    Flightnr: 'FLT-123',
    Date: '16/01/2024',
    'Aircraft Type': 'Boeing 747',
    Tail: 'XYZ789',
    Departure: 'AMS',
    Destination: 'ATH',
    Time_Depart: '10:00 AM',
    Time_Arrive: '12:00 PM',
    DutyID: 'FLT',
    DutyCode: 'DC456',
    Captain: 'John Doe',
    'First Officer': 'Jane Smith',
    'Flight Attendant': 'Alice Johnson',
  },
  {
    Flightnr: 'FLT-456',
    Date: '22/01/2024',
    'Aircraft Type': 'Airbus A320',
    Tail: 'ABC123',
    Departure: 'JFK',
    Destination: 'LHR',
    Time_Depart: '08:30 AM',
    Time_Arrive: '11:45 AM',
    DutyID: 'SBY',
    DutyCode: 'DC789',
    Captain: 'Michael Brown',
    'First Officer': 'Emily Davis',
    'Flight Attendant': 'Bob Wilson',
  },
  {
    Flightnr: 'FLT-123',
    Date: '21/02/2024',
    'Aircraft Type': 'Boeing 747',
    Tail: 'XYZ789',
    Departure: 'AMS',
    Destination: 'ATH',
    Time_Depart: '10:00 AM',
    Time_Arrive: '12:00 PM',
    DutyID: 'OFD',
    DutyCode: 'DC456',
    Captain: 'John Doe',
    'First Officer': 'Jane Smith',
    'Flight Attendant': 'Alice Johnson',
  },
  {
    Flightnr: 'FLT-456',
    Date: '21/02/2024',
    'Aircraft Type': 'Airbus A320',
    Tail: 'ABC123',
    Departure: 'JFK',
    Destination: 'LHR',
    Time_Depart: '08:30 AM',
    Time_Arrive: '11:45 AM',
    DutyID: 'SBY',
    DutyCode: 'DC789',
    Captain: 'Michael Brown',
    'First Officer': 'Emily Davis',
    'Flight Attendant': 'Bob Wilson',
  },
  {
    Flightnr: 'FLT-123',
    Date: '02/01/2024',
    'Aircraft Type': 'Boeing 747',
    Tail: 'XYZ789',
    Departure: 'AMS',
    Destination: 'ATH',
    Time_Depart: '10:00 AM',
    Time_Arrive: '12:00 PM',
    DutyID: 'FLT',
    DutyCode: 'DC456',
    Captain: 'John Doe',
    'First Officer': 'Jane Smith',
    'Flight Attendant': 'Alice Johnson',
  },
  {
    Flightnr: 'FLT-456',
    Date: '18/09/2024',
    'Aircraft Type': 'Airbus A320',
    Tail: 'ABC123',
    Departure: 'JFK',
    Destination: 'LHR',
    Time_Depart: '08:30 AM',
    Time_Arrive: '11:45 AM',
    DutyID: 'OFD',
    DutyCode: 'DC789',
    Captain: 'Michael Brown',
    'First Officer': 'Emily Davis',
    'Flight Attendant': 'Bob Wilson',
  },
];
